spring.application.name=SelfTop_web

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@selftop_medium?TNS_ADMIN=E:\\\\SelfTop_data\\\\Wallet_SELFTOP
spring.datasource.username=ADMIN
spring.datasource.password=SelfTop040404